accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MPL-2.0",
    "OFL-1.1",
    "OpenSSL",
    "Unlicense",
    "Zlib",
    "zlib-acknowledgement",
    "Unicode-DFS-2016",
    "Unicode-3.0",
]

targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "aarch64-linux-android",
    "wasm32-unknown-unknown",
]

workarounds = ["ring"]
